seajs.config({
  base: 'http://i2.sinaimg.cn/jslib/modules2/'
  ,alias: {
    //gallery
    'jquery': 'gallery/jquery/1.8.2/jquery'
    ,'$': 'gallery/jquery/1.8.2/jquery'
    ,'async': 'gallery/async/0.1.23/async'
    ,'backbone': 'gallery/backbone/0.9.2/backbone'
    ,'coffee': 'gallery/coffee/1.4.0/coffee-script'
    ,'cookie': 'gallery/cookie/1.0.2/cookie'
    ,'es5-safe': 'gallery/es5-safe/0.9.2/es5-safe'
    ,'handlebars': 'gallery/handlebars/1.0.0/handlebars'
    ,'iscroll': 'gallery/iscroll/4.2.5/iscroll'
    ,'jasmine-jquery': 'gallery/jasmine-jquery/1.4.2/jasmine-jquery'
    ,'jasmine': 'gallery/jasmine/1.2.0/jasmine'
    ,'jquery-color': 'gallery/jquery-color/2.1.0/jquery-color'
    ,'json': 'gallery/json/1.0.2/json'
    ,'keymaster': 'gallery/keymaster/1.0.2/keymaster'
    ,'labjs': 'gallery/labjs/2.0.3/lab'
    ,'less': 'gallery/less/1.3.1/less'
    ,'marked': 'gallery/marked/0.2.4/marked'
    ,'moment': 'gallery/moment/1.7.2/moment'
    ,'mustache': 'gallery/mustache/0.5.0/mustache'
    ,'querystring': 'gallery/querystring/1.0.2/querystring'
    ,'raphael': 'gallery/raphael/2.1.0/raphael'
    ,'socketio': 'gallery/socketio/0.9.6/socketio'
    ,'store': 'gallery/store/1.3.5/store'
    ,'swfobject': 'gallery/swfobject/2.2.0/swfobject'
    ,'underscore': 'gallery/underscore/1.4.2/underscore'
    ,'zepto': 'gallery/zepto/1.0.0/zepto'
    ,'ztree': 'gallery/ztree/3.4.1/ztree'
    //sina
    ,'sina.util': 'sina/util/1.0.5/util'
    ,'sina.flashData': 'sina/flashData/1.0.0/flashData'
    ,'sina.permanent': 'sina/permanent/1.0.0/permanent'
    ,'sina.FocusPic': 'sina/FocusPic/1.0.1/FocusPic'
    ,'sina.ScrollPic': 'sina/ScrollPic/1.0.0/ScrollPic'
    ,'sina.SubShow': 'sina/SubShow/1.0.0/SubShow'
    ,'sina.ImageSlide': 'sina/ImageSlide/1.0.0/ImageSlide'
    ,'sina.test': 'sina/test/1.0.1/test'
  }
  ,charset: 'utf-8'
});